import jsPDF from "jspdf";
import "jspdf-autotable";
import html2canvas from "html2canvas";

// Check if jsPDF is available
const isJSPDFAvailable = () => {
  try {
    return typeof jsPDF !== "undefined" && jsPDF;
  } catch (error) {
    console.error("jsPDF not available:", error);
    return false;
  }
};

// Simple CSV export as fallback
const exportToCSV = (report) => {
  try {
    // Create CSV content
    const csvRows = [];

    // Header
    csvRows.push("AIRE Vault - Anonymous Incident Report");
    csvRows.push("Confidential Report - For Authorized NGO Use Only");
    csvRows.push("");

    // Report Information
    csvRows.push("REPORT INFORMATION");
    csvRows.push(`Report ID,${report.reportId}`);
    csvRows.push(`Generated Date,${new Date().toLocaleString()}`);
    csvRows.push(
      `Original Report Date,${new Date(report.createdAt).toLocaleString()}`
    );
    csvRows.push("");

    // Incident Details
    csvRows.push("INCIDENT DETAILS");
    csvRows.push(`Incident Title,${report.incidentTitle || "N/A"}`);
    csvRows.push(`Incident Type,${report.incidentType || "General"}`);
    csvRows.push(`Urgency Level,${report.urgencyLevel || "Normal"}`);
    csvRows.push(
      `Date & Time,${
        report.dateTime ? new Date(report.dateTime).toLocaleString() : "N/A"
      }`
    );
    csvRows.push(`Location,${report.location || "N/A"}`);
    csvRows.push(`Report Status,${report.status || "pending"}`);
    if (report.PhoneNumber)
      csvRows.push(`Contact Number,${report.PhoneNumber}`);
    csvRows.push(
      `Consent to Share with NGOs,${
        report.consentToShareWithNGO ? "Yes" : "No"
      }`
    );
    csvRows.push("");

    // Description
    csvRows.push("INCIDENT DESCRIPTION");
    // Escape quotes in description
    const safeDescription = (
      report.description || "No description provided."
    ).replace(/"/g, '""');
    csvRows.push(`"${safeDescription}"`);
    csvRows.push("");

    // Evidence URLs
    if (report.evidenceUrls && report.evidenceUrls.length > 0) {
      csvRows.push(`EVIDENCE FILES (${report.evidenceUrls.length})`);
      report.evidenceUrls.forEach((url, index) => {
        csvRows.push(`File ${index + 1},"${url}"`);
      });
      csvRows.push("");
    }

    // Footer
    csvRows.push("");
    csvRows.push("--- END OF REPORT ---");
    csvRows.push("Generated by AIRE Vault System");
    csvRows.push("All data is encrypted and anonymized for security purposes");

    // Create CSV string
    const csvString = csvRows.join("\n");

    // Create blob and download
    const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Report_${report.reportId}_${
      new Date().toISOString().split("T")[0]
    }.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    return true;
  } catch (error) {
    console.error("Error exporting to CSV:", error);
    throw error;
  }
};

// Function to generate PDF report with fallback
export const generatePDFReport = (report) => {
  try {
    // First try to use jsPDF if available
    if (isJSPDFAvailable()) {
      const doc = new jsPDF();

      // Add logo/header
      doc.setFontSize(20);
      doc.setTextColor(40, 53, 147);
      doc.text("AIRE Vault - Anonymous Incident Report", 20, 20);

      doc.setFontSize(10);
      doc.setTextColor(128, 128, 128);
      doc.text("Confidential Report - For Authorized NGO Use Only", 20, 30);

      // Add report ID
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Report ID: ${report.reportId}`, 20, 45);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 150, 45);

      // Incident Details - Using manual table since autotable might not be available
      doc.setFontSize(14);
      doc.setTextColor(40, 53, 147);
      doc.text("1. Incident Details", 20, 60);

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);

      let yPos = 70;

      // Manually add details as text
      doc.text(`Incident Title: ${report.incidentTitle || "N/A"}`, 20, yPos);
      yPos += 7;
      doc.text(`Incident Type: ${report.incidentType || "General"}`, 20, yPos);
      yPos += 7;
      doc.text(`Urgency Level: ${report.urgencyLevel || "Normal"}`, 20, yPos);
      yPos += 7;
      doc.text(
        `Date & Time: ${
          report.dateTime ? new Date(report.dateTime).toLocaleString() : "N/A"
        }`,
        20,
        yPos
      );
      yPos += 7;
      doc.text(`Location: ${report.location || "N/A"}`, 20, yPos);
      yPos += 7;
      doc.text(`Report Status: ${report.status || "pending"}`, 20, yPos);
      yPos += 7;

      if (report.PhoneNumber) {
        doc.text(`Contact Number: ${report.PhoneNumber}`, 20, yPos);
        yPos += 7;
      }

      doc.text(
        `Consent to Share: ${report.consentToShareWithNGO ? "Yes" : "No"}`,
        20,
        yPos
      );
      yPos += 7;
      doc.text(
        `Created: ${
          report.createdAt
            ? new Date(report.createdAt).toLocaleDateString()
            : "N/A"
        }`,
        20,
        yPos
      );
      yPos += 10;

      // Description
      doc.setFontSize(14);
      doc.setTextColor(40, 53, 147);
      doc.text("2. Incident Description", 20, yPos);
      yPos += 7;

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);

      const description = report.description || "No description provided.";
      const splitDescription = doc.splitTextToSize(description, 170);
      doc.text(splitDescription, 20, yPos);
      yPos += splitDescription.length * 5 + 10;

      // Evidence URLs
      if (report.evidenceUrls && report.evidenceUrls.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(40, 53, 147);
        doc.text("3. Evidence Files", 20, yPos);
        yPos += 7;

        doc.setFontSize(10);
        doc.setTextColor(0, 0, 0);

        report.evidenceUrls.forEach((url, index) => {
          const urlText = `${index + 1}. ${url}`;
          const splitUrl = doc.splitTextToSize(urlText, 170);
          doc.text(splitUrl, 20, yPos);
          yPos += splitUrl.length * 5 + 3;

          // Add page break if needed
          if (yPos > 250) {
            doc.addPage();
            yPos = 20;
          }
        });
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      const footerY = doc.internal.pageSize.height - 20;
      doc.text(
        "This document is automatically generated by AIRE Vault System.",
        20,
        footerY
      );
      doc.text(
        "All data is encrypted and anonymized for security purposes.",
        20,
        footerY - 5
      );
      doc.text(`Document ID: ${Date.now()}`, 20, footerY - 10);

      // Save the PDF
      const fileName = `Report_${report.reportId}_${
        new Date().toISOString().split("T")[0]
      }.pdf`;
      doc.save(fileName);

      return fileName;
    } else {
      // Fallback to CSV if jsPDF is not available
      console.warn("jsPDF not available, falling back to CSV export");
      return exportToCSV(report);
    }
  } catch (error) {
    console.error("Error in generatePDFReport:", error);
    // Fallback to CSV on error
    try {
      return exportToCSV(report);
    } catch (fallbackError) {
      console.error("Even CSV fallback failed:", fallbackError);
      throw new Error("Failed to generate report. Please try again.");
    }
  }
};

// Alternative: Generate HTML report for printing
export const generateHTMLReport = (report) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>AIRE Vault Report - ${report.reportId}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { color: #283593; border-bottom: 2px solid #283593; padding-bottom: 10px; margin-bottom: 30px; }
        .section { margin-bottom: 25px; }
        .section-title { color: #283593; font-size: 18px; font-weight: bold; margin-bottom: 10px; }
        .detail-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .detail-table th, .detail-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .detail-table th { background-color: #283593; color: white; }
        .description { background-color: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .evidence-list { margin-left: 20px; }
        .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
        @media print {
          body { margin: 0; }
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>AIRE Vault - Anonymous Incident Report</h1>
        <p>Confidential Report - For Authorized NGO Use Only</p>
      </div>
      
      <div class="section">
        <h2 class="section-title">Report Information</h2>
        <table class="detail-table">
          <tr><th>Report ID</th><td>${report.reportId}</td></tr>
          <tr><th>Generated Date</th><td>${new Date().toLocaleString()}</td></tr>
          <tr><th>Original Report Date</th><td>${new Date(
            report.createdAt
          ).toLocaleString()}</td></tr>
        </table>
      </div>
      
      <div class="section">
        <h2 class="section-title">Incident Details</h2>
        <table class="detail-table">
          <tr><th>Incident Title</th><td>${
            report.incidentTitle || "N/A"
          }</td></tr>
          <tr><th>Incident Type</th><td>${
            report.incidentType || "General"
          }</td></tr>
          <tr><th>Urgency Level</th><td>${
            report.urgencyLevel || "Normal"
          }</td></tr>
          <tr><th>Date & Time</th><td>${
            report.dateTime ? new Date(report.dateTime).toLocaleString() : "N/A"
          }</td></tr>
          <tr><th>Location</th><td>${report.location || "N/A"}</td></tr>
          <tr><th>Report Status</th><td>${report.status || "pending"}</td></tr>
          ${
            report.PhoneNumber
              ? `<tr><th>Contact Number</th><td>${report.PhoneNumber}</td></tr>`
              : ""
          }
          <tr><th>Consent to Share with NGOs</th><td>${
            report.consentToShareWithNGO ? "Yes" : "No"
          }</td></tr>
        </table>
      </div>
      
      <div class="section">
        <h2 class="section-title">Incident Description</h2>
        <div class="description">${
          report.description || "No description provided."
        }</div>
      </div>
      
      ${
        report.evidenceUrls && report.evidenceUrls.length > 0
          ? `
      <div class="section">
        <h2 class="section-title">Evidence Files (${
          report.evidenceUrls.length
        })</h2>
        <ol class="evidence-list">
          ${report.evidenceUrls
            .map(
              (url, index) => `
            <li><a href="${url}" target="_blank">${url}</a></li>
          `
            )
            .join("")}
        </ol>
      </div>
      `
          : ""
      }
      
      <div class="footer">
        <p>This document is automatically generated by AIRE Vault System.</p>
        <p>All data is encrypted and anonymized for security purposes.</p>
        <p>Document ID: ${Date.now()}</p>
        <button class="no-print" onclick="window.print()">Print Report</button>
      </div>
    </body>
    </html>
  `;

  return htmlContent;
};

// Function to download report as text file
export const downloadTextReport = (report) => {
  let textContent = `AIRE Vault - Anonymous Incident Report\n`;
  textContent += `========================================\n\n`;
  textContent += `Report ID: ${report.reportId}\n`;
  textContent += `Generated: ${new Date().toLocaleString()}\n\n`;

  textContent += `INCIDENT DETAILS\n`;
  textContent += `----------------\n`;
  textContent += `Title: ${report.incidentTitle || "N/A"}\n`;
  textContent += `Type: ${report.incidentType || "General"}\n`;
  textContent += `Urgency: ${report.urgencyLevel || "Normal"}\n`;
  textContent += `Date & Time: ${
    report.dateTime ? new Date(report.dateTime).toLocaleString() : "N/A"
  }\n`;
  textContent += `Location: ${report.location || "N/A"}\n`;
  textContent += `Status: ${report.status || "pending"}\n`;
  if (report.PhoneNumber) textContent += `Contact: ${report.PhoneNumber}\n`;
  textContent += `Consent to Share: ${
    report.consentToShareWithNGO ? "Yes" : "No"
  }\n`;
  textContent += `Created: ${new Date(
    report.createdAt
  ).toLocaleDateString()}\n\n`;

  textContent += `DESCRIPTION\n`;
  textContent += `-----------\n`;
  textContent += `${report.description || "No description provided."}\n\n`;

  if (report.evidenceUrls && report.evidenceUrls.length > 0) {
    textContent += `EVIDENCE FILES (${report.evidenceUrls.length})\n`;
    textContent += `---------------\n`;
    report.evidenceUrls.forEach((url, index) => {
      textContent += `${index + 1}. ${url}\n`;
    });
    textContent += `\n`;
  }

  textContent += `\n--- END OF REPORT ---\n`;
  textContent += `Generated by AIRE Vault System\n`;
  textContent += `All data is encrypted and anonymized`;

  const blob = new Blob([textContent], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `Report_${report.reportId}_${
    new Date().toISOString().split("T")[0]
  }.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
